version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo hola! > sayhi.txt
      - echo oi! >> sayhi.txt
      - echo halo! >> sayhi.txt
      - echo ciao! >> sayhi.txt
      - echo hello! >> sayhi.txt
      - echo sasasasasasasasasa! >> sayhi.txt
      - cat sayhi.txt
artifacts: 
  files: 
    - sayhi.txt
