version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo "Ultima prueba y salimos andando como loco y danzando!"
      - echo hola! > sayhi.txt
      - ls -lah
artifacts: 
  files: 
    - sayhi.txt
