version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo "Una prueba..."
      - echo hola! > sayhi.txt
      - echo oi! >> sayhi.txt
      - cat sayhi.txt
artifacts: 
  files: 
    - sayhi.txt
